In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encodeur=OneHotEncoder()

In [ ]:
X=[['chat','poil'],['chien','poil'],['poule', 'plume'],['faisan','plume']]

In [ ]:
Xtransform=encodeur.fit_transform(X)

In [ ]:
Xtransform

<4x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
Xtransform.toarray()

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1., 0.]])

In [ ]:
Xorigine=encodeur.inverse_transform(Xtransform)

In [ ]:
Xorigine

array([['chat', 'poil'],
       ['chien', 'poil'],
       ['poule', 'plume'],
       ['faisan', 'plume']], dtype=object)

In [ ]:
X2=[[0, 0.5], [0.5, -0.5], [1, -1], [1, 1]]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
Xscale=scaler.fit_transform(X2)

In [ ]:
print(Xscale)

[[-1.50755672  0.63245553]
 [-0.30151134 -0.63245553]
 [ 0.90453403 -1.26491106]
 [ 0.90453403  1.26491106]]


In [ ]:
print(scaler.inverse_transform(Xscale))

[[ 0.   0.5]
 [ 0.5 -0.5]
 [ 1.  -1. ]
 [ 1.   1. ]]
